# 공통 설정파일 - 필요 설정은 하위 환경 설정파일에서 오버라이딩

spring:
  application:
    name: chat

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(gkzJV5HUytLIBkRclZlitVPI4+kGmpXHfqjb5gYFUGS+ERvwmgNRgL2VnRF9sPVk9cDLM599axKdJIFhEnjOMYBH1zUwfe5kuKpo5+6JYnJoUBo2pxom3A==)
            client-secret: ENC(FUMnuBKFHX6iaRZGZrYOzf6WHkTnPGVGV839zDbNhhyfIn5J27gtTtMiVSxgyNQpBnqCoSSw5Kk=)
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: profile, email

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(NJoE4qQ/KWpucJHkzytoOLoDsOAifyKuL68x2C0QSiMU3ZdRkakgvmbaU62bezIn628k3DK/S7OH29RUUXTNcyLCti8nbqXe)
    username: ENC(rwefQlhEi81aBX/iYwXRBSst4/x5+xcA)
    password: ENC(+Tm0Pp03+9KGocszzdLJm4HjBRq0ZaL51LGhLtff9jw=)
#    url: ENC(fSDS36X8Mv27i3wnvomVScbNmWqq83X5u4SI8bMY/3Rt6nSd6I5SuMFQH6PKxhx7TcoBAiwoQQLSMyPu89m6hUk98w+9Hiaz00o0m2FrlEfUZyt6a6pGesVVuExJMHQ3TYhiSHxyKkvHZjxhMEwPRAfMA73nP7xYoY3YTcrIYjQ=)
#    username: ENC(iVDQ7GIAA0QCDh9Owp3VfqxaMKxj9ySUSEV088JDr3k=)
#    password: ENC(UTnnyYwPD1t4UD1kjk5o/wyxpMo1bWc9Y8m667sF1b4=)

  jpa:
    show-sql: false

    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100 # batch 처리(update, insert)시 N + 1 해결

    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true

server:
  servlet:
    context-path: /api/v1/


jwt:
  secret-key-base: ENC(vZ9d0WvdGFFU7iC/NyQTlX3Q2K3fqr1l2RUZL+uUBRNZS0wLFk3X7XmoSmwTuKMB3Z2LEXyeUGTX8K3xZxvQNRFdDOSF/xVLrTb4kXj/NUD4gXAFLFtrtByC95JH5jtDq5bXViEDITSjYJfL/kv6gA==)

app:
  oauth2:
    authorized-redirect-uris: http://localhost:3000/oauth/redirect