spring:
  application:
    name: chat

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 83652550395-qu7f06ijctmjghlr2tj8hlt4gjfj1692.apps.googleusercontent.com
            client-secret: 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
            scope: # google API ? ?? ?
              - profile
              - email

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n2566-kr.vpc-pub-cdb.ntruss.com:3306/mysql_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mysql_dba
    password: gotka9080!
  # TODO datasource url, username, password ??? ??

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true # ?? ????
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true # ????? actuator api ????

server:
  servlet:
    context-path: /v1/


jwt:
  secret_key_base: ENC(SHV+duWjEpL+JiE+sCzC0JwVfjcSvey5T9Ij7OKoqdFxBqgkhj53Iwp0lq+mS+MbemHJ+kVKvDvnSUwjpv0O+JfwKo3S/Zp4SNDlh5DbVgD5F1aL4YApAk2YvkWf++A28pHEfOxiwcHQn8OWIJHqOH9SGaTRbUg6R7lsLqTd4MihhSN4nGIm5DRKXx3niHkzED+6Fq3fnXI=)