spring:
  application:
    name: chat

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n2566-kr.vpc-pub-cdb.ntruss.com:3306/mysql_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mysql_dba
    password: gotka9080!
  # TODO datasource url, username, password ??? ??

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true # ?? ????
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true # ????? actuator api ????

server:
  servlet:
    context-path: /api/v1/